{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "claude-apps-gateway.namespace" . }}
  labels:
    kubernetes.io/metadata.name: {{ include "claude-apps-gateway.namespace" . }}
{{- end }}
